### ISSUE TITLE
logstash pipeline stopped

### ISSUE THREAD

**Issue by lsj4401** [logstash-plugins/logstash-filter-urldecode#5]
Logstash dies during the encoding process :(
I think, The following conditions must return a warning Message, do not process stop

Input : 
`127.0.0.1  -       -       [06/Apr/2016:15:39:11 +0900]    GET     localhost:8080=news&option=accu&qm=f_typing&query=%EB%AC%B8%EC%9E%AC%EC%9D%B8êµ­ë¯¼ì<9d>¼ë³´  HTTP/1.1        200     -       -       "Mozilla"       "-"
`
ErrorMessage : 

> Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>#<Encoding::CompatibilityError: incompatible encodings: ASCII-8BIT and UTF-8>, "backtrace"=>["org/jruby/RubyString.java:3064:in `gsub'", "/opt/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:331:in`unescape'", "/opt/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:649:in `unescape'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-2.0.4/lib/logstash/filters/urldecode.rb:50:in`urldecode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-2.0.4/lib/logstash/filters/urldecode.rb:39:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/filters/base.rb:151:in`multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/filters/base.rb:148:in`multi_filter'", "(eval):98:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:267:in`filter_batch'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in`inject'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:265:in `filter_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:223:in`worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}

thank you.

**Comment by andrewvc** [comment]
Thanks for opening the issue, but questions about usage should be asked on https://discuss.elastic.co/c/logstash . 

We only use github issues are for bug reports and feature requests only.
