### ISSUE TITLE
"exception"=>#<Encoding::CompatibilityError: incompatible encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by zhaochl** [logstash-plugins/logstash-filter-urldecode#8]
Hi guys ,I have a problem as follows, which makes logstash so unstable, logstash exit strangely 
version 2..4.1
Thanks  for any response.

----logs--
{:timestamp=>"2017-03-29T14:40:29.456000+0800", :message=>"Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.", "exception"=>#<Encoding::CompatibilityError: incompatible encodings: UTF-8 and ASCII-8BIT>, "backtrace"=>["org/jruby/RubyString.java:3064:in `gsub'", "/home/work/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:331:in `unescape'", "/home/work/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:649:in `unescape'", "/home/work/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-2.0.4/lib/logstash/filters/urldecode.rb:50:in `urldecode'", "/home/work/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-2.0.4/lib/logstash/filters/urldecode.rb:39:in `filter'", "/home/work/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/filters/base.rb:151:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/work/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/filters/base.rb:148:in `multi_filter'", "(eval):155:in `filter_func'", "/home/work/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:267:in `filter_batch'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in `inject'", "/home/work/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:265:in `filter_batch'", "/home/work/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:223:in `worker_loop'", "/home/work/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}

**Comment by guyboertje** [comment]
See this issue and comment for the fix. https://github.com/logstash-plugins/logstash-filter-urldecode/issues/6#issuecomment-284011661

**Comment by guyboertje** [comment]
I have fixed this properly in version 3.0.3

**Comment by zhaochl** [comment]
great. I had improved my logstash version to the latest one.
